dict_municipios = {'Ajalvir': 'IAJALV3',
 'El Álamo': 'IMORAL25',
 'Alcalá de Henares': 'IALBACET33',
 'Alcobendas': 'IALCOB23',
 'Alcorcón': 'IALCORCN13',
 'Algete': 'IALGET4',
 'Alpedrete': 'IALPED10',
 'Aranjuez': 'IARANJ4',
 'Arganda del Rey': 'IARGAN15',
 'Batres': 'IBATRE1',
 'Becerril de la Sierra': 'IBECER12',
 'Boadilla del Monte': 'IBOADI12',
 'El Boalo': 'IELBOA16',
 'Brunete': 'IBRUNE25',
 'Buitrago del Lozoya': 'IBUITR2',
 'Bustarviejo': 'IBUSTA12',
 'Cabanillas de la Sierra': 'ICABAN28',
 'Talofofo': 'IMCHUECA17',
 'Camarma de Esteruelas': 'ICAMAR23',
 'Cercedilla': 'ICERCE16',
 'Chinchón': 'ICHINC15',
 'Ciempozuelos': 'ICIEMP5',
 'Cobeña': 'ICOBEA3',
 'Collado Mediano': 'ICOLLA20',
 'Collado Villalba': 'ICOLLA28',
 'Colmenar de Oreja': 'ICOLME38',
 'Colmenarejo': 'ICOLME74',
 'Colmenar Viejo': 'ICOLME91',
 'Coslada': 'ICOSLA10',
 'Cubas de la Sagra': 'ICUBAS2',
 'Daganzo de Arriba': 'IDAGAN9',
 'Real Monasterio de San Lorenzo de El Escorial': 'IELESC10',
 'Fuenlabrada': 'IFUENLAB14',
 'Fuente el Saz de Jarama': 'IFUENT45',
 'Galapagar': 'IGALAP24',
 'Gascones': 'IVILLA424',
 'Getafe': 'IMADRIDG2',
 'Griñón': 'IGRIN2',
 'Guadalix de la Sierra': 'IGUADA34',
 'Guadarrama': 'IGUADARR14',
 'Hoyo de Manzanares': 'IHOYODEM5',
 'Humanes de Madrid': 'IGRIN2',
 'Loeches': '100C lite',
 'Madrid': 'IMCHUECA17',
 'Majadahonda': 'IMAJAD32',
 'Manzanares el Real': 'IMANZA19',
 'Meco': 'IMECO5',
 'Mejorada del Campo': 'IMEJOR4',
 'El Molar': 'IELMOL3',
 'Moralzarzal': 'IMORALZA8',
 'Morata de Tajuña': 'IMORAT67',
 'Móstoles': 'IMSTOL16',
 'Navacerrada': 'INAVAC1',
 'Navalagamella': 'IVALDE238',
 'Navalcarnero': 'INAVAL17',
 'Navas del Rey': 'INAVAS9',
 'Nuevo Baztán': 'INUEVO30',
 'Orusco de Tajuña': 'IVILLA1123',
 'Paracuellos de Jarama': 'IPARAC71',
 'Parla': 'IPARLA26',
 'Patones': 'ITORRE333',
 'Pedrezuela': 'IPEDRE32',
 'Pinto': 'IPINTO9',
 'Pozuelo de Alarcón': 'IPOZUE41',
 'Quijorna': 'IQUIJO1',
 'Rascafría': 'IRASCA5',
 'Rivas-Vaciamadrid': 'IRIVAS87',
 'Robledo de Chavela': 'IROBLE35',
 'Las Rozas de Madrid': 'Alto de la Jabonería',
 'San Agustín del Guadalix': 'ISANAG23',
 'San Fernando de Henares': 'ISANFE116',
 'San Lorenzo de El Escorial': 'IELESC10',
 'San Martín de la Vega': 'ICIEMP5',
 'San Martín de Valdeiglesias': 'ISANMA103',
 'San Sebastián de los Reyes': 'ISANSE135',
 'Los Santos de la Humosa': 'ILOSSA31',
 'Serranillos del Valle': 'ISERRA76',
 'Sevilla la Nueva': 'ICOMUNID317',
 'Soto del Real': 'ISOTOD29',
 'Talamanca de Jarama': 'ITALAM7',
 'Torrejón de Ardoz': 'Torrejón de Ardoz',
 'Torrejón de la Calzada': '1',
 'Torrejón de Velasco': 'ITORRE334',
 'Torrelaguna': 'ITORRE406',
 'Torrelodones': 'ITORRE413',
 'Torres de la Alameda': 'ITORRE158',
 'Tres Cantos': 'ITRESC2',
 'Valdemoro': 'IVALDE265',
 'Valdepiélagos': 'IVALDE302',
 'Valdilecha': 'ITIELM1',
 'Valverde de Alcalá': 'IVILLA1379',
 'Villalbilla': 'IVILLA1379',
 'Villamanrique de Tajo': 'IFUENT87',
 'Villanueva de la Cañada': 'IVILLA984',
 'Villanueva del Pardillo': 'IVILLA1325',
 'Villarejo de Salvanés': 'IBELMO62',
 'Villaviciosa de Odón': 'IVILLA777',
 'Zarzalejo (estación)': 'IZARZA9'}